backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "Home"
    folder: "content/"
    create: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Header"
        name: "header"
        widget: "string"
      - label: "Subheader"
        name: "subheader"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
          