backend:
  name: git-gateway
  branch: __BRANCH__

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "Home"
    folder: "content/_index.md"
    create: false
    fields:
      - label: "Body"
        name: "body"
        widget: "markdown"
          